package com.paw2go.adminjwt.Controller;

import com.paw2go.adminjwt.Model.AuthenticationRequest;
import com.paw2go.adminjwt.Model.AuthenticationResponse;
import com.paw2go.adminjwt.Model.Admin;
import com.paw2go.adminjwt.Repository.AdminRepository;
import com.paw2go.adminjwt.Services.MyUserDetailsService;
import com.paw2go.adminjwt.Services.UserService;
import com.paw2go.adminjwt.Util.JwtUtil;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/admin") // This means URL's start with /demo (after Application path)
public class AdminController {
    @Autowired // This means to get the bean called adminRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AdminRepository adminRepository;

    @Autowired
    private AuthenticationManager authenticationManager;

    @Autowired
    private MyUserDetailsService miUserDetailsService;

    @Autowired
    private JwtUtil jwtTokenUtil;

    //API servicios , endpoints disponibles
    //primero se debe verificar/autentificar, sacando una jwt en
    //el endpoint /verificacion con metodo POST y en el body → {"username":"correo de algun usuario en la database", "password":"el contraseña de ese usuario"
    //usar el jwt en el header = key Authorization  value "Bearer Aqui el jwt que se genero"

    //http://localhost:8080/admin/admintoken
    @PostMapping(path = "/admintoken")
    //GENERAR TOKEN JWT solo a usuarios registrados http//localhost:8080/verificacion
    public ResponseEntity<?> generarTokenVerificacion(@RequestBody AuthenticationRequest solicitudVerificacion) throws Exception {
        try {
            authenticationManager.authenticate(
                    new UsernamePasswordAuthenticationToken(solicitudVerificacion.getUsername(), solicitudVerificacion.getPassword())
            );
        } catch (BadCredentialsException e) {
            throw new Exception("No se encontro ningun usuario con el correo: " + solicitudVerificacion.getUsername(), e);
        }


        final UserDetails miUsuarioDetalles = miUserDetailsService
                .loadUserByUsername(solicitudVerificacion.getUsername());//get correo, verifica correo no nombre

        final String jwt = jwtTokenUtil.generateToken(miUsuarioDetalles);

        return ResponseEntity.ok(new AuthenticationResponse(jwt));
    }

    //http://localhost:8080/admin/dispalyall
    @GetMapping(path = "/dispalyall") //MUESTRA TODOS LOS USUARIOS  http://localhost:8080/dispalyall
    public @ResponseBody
    ResponseEntity<Iterable<Admin>> getAllUsers() {
        // This returns a JSON or XML with the users
        return new ResponseEntity<>(adminRepository.findAll(), HttpStatus.OK);
    }

    //http://localhost:8080/admin/dispalyadmin/id
    @GetMapping(path = "/dispalyadmin/{id}") //MUESTRA SOLO UN USUARIO
    public ResponseEntity<Object> getUser(@PathVariable int id) {
        if (adminRepository.existsById(id)) {
            return new ResponseEntity<>(adminRepository.findById(id), HttpStatus.OK);
        } else {
            return new ResponseEntity<>("El usuario con el id: " + id + " No existe", HttpStatus.NOT_FOUND);
        }
    }

    //http://localhost:8080/admin/newuser
    @PostMapping(path = "/newuser") // Map ONLY POST Requests
    public ResponseEntity<Object> addNewUser(@RequestBody Admin admin) {
        adminRepository.save(admin);
        return new ResponseEntity<>("El usuario\n" + "con el id:" + admin.getIdAdmin() + " " + admin.getAdminName() + "  " + admin.getAdminEmail() + "\nSe ha registrado con etxsito", HttpStatus.CREATED);
    }

    //http://localhost:8080/admin/update/id
    @PutMapping(path = "/update/{id}") //Actualizar registro
    public ResponseEntity<Object> updateUser(@PathVariable int id, @RequestBody Admin admin) {
        Admin nuevo = new Admin();
        nuevo = adminRepository.findByIdAdmin(id);
        nuevo.setIdAdmin(admin.getIdAdmin());
        nuevo.setAdminName(admin.getAdminName());
        nuevo.setAdminEmail(admin.getAdminEmail());
        nuevo.setAdminUsername(admin.getAdminUsername());
        nuevo.setAdminPassword(admin.getAdminPassword());
        adminRepository.save(nuevo);
        return new ResponseEntity<>("Usuario: " + id + "\n fue actualizado exitosamente", HttpStatus.ACCEPTED);
        //"El usuario: "+adminRepository.findById(id)+" se ha actualizado";
    }

    //http://localhost:8080/admin/deleteadmin/id
    @DeleteMapping(path = "/deleteadmin/{id}") //ELIMINA UN ADMINISTRADOR
    public @ResponseBody
    String deleteUser(@PathVariable Integer id) {
        adminRepository.deleteById(id);
        return "Adminsitrator con id: " + id + " Se ha borrado de la databeis pá siempre";//no va a encontrar a nadie porque ya esta borrado
    }
}